# fly.toml file generated for wireguard-example on 2020-11-11T17:20:55-06:00

app = "wireguard-example"

[[services]]
  internal_port = 5556
  protocol = "udp"

  [[services.ports]]
    port = "5556"
